### ISSUE TITLE
Enhance content for /reporting/#analytics

### ISSUE THREAD

**Issue by grantmiller** [enterpriseready/enterpriseready#164]
Please help create the content for the reporting page (https://www.enterpriseready.io/features/advanced-reporting/) that directs SaaS companies on how to best implement analytics into their application.

**Comment by ernestoongaro** [comment]
I've got a start here - will add example(s) in couple days https://github.com/ernestoongaro/enterpriseready/commit/e98cce57f3a8cfb86389f7c1fb4c1228f205251c
