### ISSUE TITLE
Create a reporting implementation example (Github)

### ISSUE THREAD

**Issue by grantmiller** [enterpriseready/enterpriseready#165]
For the reporting feature( https://www.enterpriseready.io/features/advanced-reporting/) please create a review of how GitHub Enterprise implements their reporting feature for enterprise customers: https://help.github.com/enterprise/11.10.340/admin/articles/site-admin-dashboard/#reports

**Comment by ernestoongaro** [comment]
I can take this Grant

**Comment by grantmiller** [comment]
@ernestoongaro perfect, thanks so much!
