### ISSUE TITLE
Broken references to static resources

### ISSUE THREAD

**Issue by joklek** [enterpriseready/enterpriseready#468]
Change dbac9149e12903aef340e7fe4f66e307bee15807 removed the directory /site/, in turn removing some static content which is referenced in some of the documents (e.g. https://github.com/enterpriseready/enterpriseready/blob/master/content/gdpr/how-to-read-gdpr.md references GDPR-abridged-text-for-SaaS-Cos.pdf which can no longer be found)

EDIT: It seems like this was the only file and this is the only article that references files from that directory. 

EDIT2: Or maybe the broken references should just reference `gdpr-abridged.md`, not the pdf and all should be fine?

**Comment by breezybaldwin** [comment]
Hello, this has been fixed. Thanks for pointing it out to us!
